namespace Util
{
    public static class JwtTokenStore
    {
        public const string Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzEwODY1Yy1iNWE3LTQyNDgtYmEyNy02MGIxNTBjNjBhYTgiLCJlbWFpbCI6InN0YWZmQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN0YWZmIiwianRpIjoiNzhmNGRlYTgtMDZhMC00ZGQyLTlkM2EtZGUxMjEyZGEwMjRmIiwiZXhwIjoxNzUxMjc4NTYzLCJpc3MiOiJQUk4yMzEiLCJhdWQiOiJQUk4yMzEifQ.vKIPUNy3l2Q-PZsm1p3bO6TaJrKd0SiNVeVp27ppI_E";
    }
}
